### ISSUE TITLE
Add options to curlftps

### ISSUE THREAD

**Issue by G-eos** [Valuya/docker-volume-curlftpfs#5]
Hello,

I would like to add options to curlftps. Unfortunately this is not support yet. Like "-o no_verify_peer -o no_verify_hostname -o ssl_try -o enable_epsv"

I try to fork the repo and made the modification but I do not figure how to compile ... I try with a docker build command, but it does not finish correctly. Is this the good way to do ? I assume that the command in the Jenkins files it is the good direction to try ?

As it seems to not have a lot users, may there is another way to do. If someone can provide some advice it would be great !

Three option for me:
- find another way
- fix and compile
- someone does the job

:)

Thanks

**Comment by G-eos** [comment]
Using the command inside jenkinsfile does the job :)
it compiles, load, enabled, volume is created but access to the volume leads to errors. Thus I will need to debug ..
If someone know where to find logs or curlftps I will love it.

**Comment by G-eos** [comment]
So ... go into the host on /var/log/daemon.log in my Debian, seems to be there :)

But, not very verbose ...
->  level=error msg=\"exit status 1\"

**Comment by cghislai** [comment]
Hi,
Sorry this plugin is not used anymore for quite some time. We had issues with zombie processes iirc.
We opted for an ftp filesystem client within our application (https://github.com/robtimus/ftp-fs).
Im going to close this issue and archive the project. I hope youll find a suitable solution for your needs.
